### ISSUE TITLE
Not a git repository

### ISSUE THREAD

**Issue by Vishal1419** [kurttheviking/git-rev-sync-js#33]
I get this error when running my project:

```
E:\Work\instachain\node_modules\git-rev-sync\index.js:20
      throw new Error('[git-rev-sync] failed to execute command: ' + result.stde
rr);
      ^

Error: [git-rev-sync] failed to execute command: fatal: Not a git repository (or
 any of the parent directories): .git

    at _command (E:\Work\instachain\node_modules\git-rev-sync\index.js:20:13)
    at Object.tag (E:\Work\instachain\node_modules\git-rev-sync\index.js:130:10)

    at Object.<anonymous> (E:/Work/instachain/webpack/dev.config.js:53:49)
    at Module._compile (module.js:570:32)
    at loader (E:\Work\instachain\node_modules\babel-register\lib\node.js:144:5)

    at Object.require.extensions.(anonymous function) [as .js] (E:\Work\instacha
in\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

I am using the latest version of git-rev-sync

Also my project directory is a git repository.

I have tried to solve this issue by changing versions of this library but still can't manage to get it to work.

Thanks for any support!!!

**Comment by Vishal1419** [comment]
sorry for posting the issue. I have initialized the git repository on another directory than this project root directory.
